import { HStack, Text, VStack, Image, Box } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import AppBar from "../components/AppBar";
import Layout from "../components/Layout";
import { PrivateLayout } from "../components/PrivateLayout";
import LandingFooter from "../features/landing/components/LandingFooter";
import LandingHero from "../features/landing/components/LandingHero";
import LandingHowItWorks from "../features/landing/components/LandingHowItWorks";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Buyonic App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack
        spacing={"0"}
        alignItems={"center"}
        w="full"
        justifyContent={"center"}
      >
        {/* TODO:  Change to a dynamic appbar */}
        <AppBar />
        <LandingHero />
        <LandingHowItWorks />
        <LandingFooter />
      </VStack>
    </Layout>
  );
};

export default Home;
