import { Text, VStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { PrivateLayout } from "../components/PrivateLayout";

const Home: NextPage = () => {
  return (
    <PrivateLayout>
      <Head>
        <title>Buyonic App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack alignItems={"center"} w="full" justifyContent={"center"}>
        <Text fontWeight={"bold"} fontSize={"3xl"}>
          Welcome to Buyonic!
        </Text>
      </VStack>
    </PrivateLayout>
  );
};

export default Home;
